// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvecdywqfmmetoiktaan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZWNkeXdxZm1tZXRvaWt0YWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDE5MjksImV4cCI6MjA3MzcxNzkyOX0.21zHRNA1WxDD2mmZ4qwNeZcvpTQGhnDqaCZWw7qnadI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});